inherit_from: configs/ScanNet/scannet.yaml
config_path: configs/ScanNet/scene0000.yaml
mapping:
  bound: [[-2.0,11.0],[-2.0,11.5],[-2.0,5.5]]
  marching_cubes_bound: [[-2.0,11.0],[-2.0,11.5],[-2.0,5.5]]
data:
  input_folder: /cluster/project/infk/courses/252-0579-00L/group10_2023/scannet/scene0000_00
  output: /scratch_net/biwidl212_second/liyueli/output/nicer-slam/ScanNet/scene0000