inherit_from: configs/ScanNet/scannet.yaml
config_path: configs/ScanNet/scene0169.yaml
mapping:
  bound: [[-0.2,9.8],[-1.0,8.5],[-1.0,3.4]]
  marching_cubes_bound: [[-0.2,9.8],[-1.0,8.5],[-1.0,3.4]]
data:
  input_folder: /cluster/project/infk/courses/252-0579-00L/group10_2023/scannet/scene0169_00
  output: /scratch_net/biwidl212_second/liyueli/output/nicer-slam/ScanNet/scene0000