inherit_from: configs/ScanNet/scannet.yaml
config_path: configs/ScanNet/scene0207.yaml
mapping:
  bound: [[0.3,9.9],[-1.0,8.0],[-1.0,3.8]]
  marching_cubes_bound: [[0.3,9.9],[-1.0,8.0],[-1.0,3.8]]
data:
  input_folder: /cluster/project/infk/courses/252-0579-00L/group10_2023/scannet/scene0207_00
  output: /scratch_net/biwidl212_second/liyueli/output/nicer-slam/ScanNet/scene0207